### ISSUE TITLE
Support Deposit IPN

### ISSUE THREAD

**Issue by SirNeural** [kevupton/laravel-coinpayments#7]
Hi, @kevupton;
At the moment, I see that the implementation for handling ipns from create_transaction calls is implemented, but not for callback_addresses, since there is no way to associate transactions by looking for the address since storing addresses not handled in the ipn model or stored in there. Is there a way to implement this functionality? Or is it already implemented and I'm looking at this wrong?

Thanks

**Comment by kevupton** [comment]
Apologies for the slow response @SirNeural 
I dont believe that IPN for callback_addresses is implemented.
Im going to have to look into see if the IPN returns any information associated with the callback_address, because it doesnt seem to have any details on their API.

I think this is a useful feature so I will implement it over the weekend 🎈

**Comment by SirNeural** [comment]
@kevupton Thanks for looking into this, if you're stuck I believe the IPN will post to the url with everything listed under a 'deposit'-type ipn, You can see what it returns here: https://www.coinpayments.net/merchant-tools-ipn#fields

**Comment by kevupton** [comment]
Ok cool thanks,
Im working on a v1 which will include this functionality, and several other things. Should be done soon hopefully.

**Comment by kevupton** [comment]
Ok cool thanks,
Im working on a v1 which will include this functionality, and several other things. Should be done soon hopefully.

**Comment by kevupton** [comment]
This is now implemented 🎈

**Comment by SirNeural** [comment]
Thanks a lot for your hard work @kevupton!
